gatePassMgmtSystem/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('adminacc/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from . import views
urlpatterns=[
	path('',views.home,name='home'),
	path('form_view',views.form_view,name='form_view'),
    path('display_data/',views.display_data,name='display_data'),
    path('edit-form/<int:item_id>/', views.edit_form_view, name='edit_form_view'),
    path('delete-form/<int:item_id>/', views.delete_form_view, name='delete_form_view'),
    path('get-districts/', views.get_districts, name='get_districts'),
    path('export-to-excel/', views.export_to_excel, name='export_to_excel'),
	path('contact',views.contact_page,name='contact_page'),

	path('accounts/signup',views.signup,name='signup'),
	path('accounts/login',views.login,name='login'),
    path('guest_login/', views.guest_login, name='guest_login'),  # Add this line


    path('add_group/', views.add_group, name='add_group'),
	path('group_list/', views.group_list, name='group_list'),
    path('group/<int:group_id>/delete/', views.delete_group, name='delete_group'),

	
	path('update_status/', views.update_status, name='update_status'),
	
	path('update-profile',views.update_profile,name='update_profile'),
	
    path('reset_user_password/', views.reset_user_password, name='reset_user_password'),
    path('get_user_data/<int:user_id>/', views.get_user_data, name='get_user_data'),
    path('cancel_update/', views.cancel_update, name='cancel_update'),
    path('update_user_profile/', views.update_user_profile, name='update_user_profile'),
    path('user_list/', views.user_list, name='user_list'),
    path('export_filter/', views.export_to_excel_filter, name='export_filter'),
    # path('generate_pie_chart/', views.generate_pie_chart, name='generate_pie_chart'),

    path('download-pdf/<int:item_id>/', views.download_pdf, name='download_pdf'),

    path('detail/<int:item_id>/', views.detail_view, name='detail_view'),


 ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.contrib.auth.models import Group  # Add this line

from . import models
from bootstrap_datepicker_plus.widgets import DatePickerInput

from django.contrib.auth.forms import AuthenticationForm

from nepali_datetime_field.forms import NepaliDateField
from django.contrib.auth import update_session_auth_hash




# class EnquiryForm(forms.ModelForm):
# 	class Meta:
# 		model=models.Enquiry
# 		fields=('full_name','email','detail')




# class ProfileForm(UserChangeForm):
# 	class Meta:
# 		model=User
# 		fields=('first_name','last_name','email','username', 'password1', 'password2')
from datetime import datetime


class CustomProfileForm(UserChangeForm):
    password1 = forms.CharField(widget=forms.PasswordInput(), label='New Password', required=False)
    password2 = forms.CharField(widget=forms.PasswordInput(), label='Confirm New Password', required=False)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

        if self.request and self.request.user.is_authenticated:
            self.fields['password1'].required = False
            self.fields['password2'].required = False
        else:
            self.fields['password1'].required = True
            self.fields['password2'].required = True

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        password1 = self.cleaned_data["password1"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.email = self.cleaned_data["email"]
        if password1:
            user.set_password(password1)
        elif 'password1' in self.changed_data:
        # If password1 is empty but it's in changed_data, clear the password
            user.set_password(None)
        if commit:
            user.save()
            update_session_auth_hash(self.request, user)
        return user


class SignUp(UserCreationForm):
	class Meta:
		model=User
		fields=('first_name','last_name','email','username','password1','password2')

	group = forms.ModelChoiceField(
        queryset=Group.objects.all(),
        label=''
    )		    








class LoginForm(AuthenticationForm):
    class Meta:
        model = User	


class UserUpdateForm(UserChangeForm):
    user_to_update = forms.ModelChoiceField(
        queryset=User.objects.all(),
        label='Select User to Update',
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        self.fields['user_to_update'].label_from_instance = lambda obj: f"{obj.username} - {obj.get_full_name()}"

    def clean_user_to_update(self):
        user_to_update = self.cleaned_data.get('user_to_update')
        if user_to_update == self.instance:
            raise forms.ValidationError("Cannot update your own profile using this form.")
        return user_to_update

    def clean(self):
        cleaned_data = super().clean()

         # Check if at least one field (excluding username) is updated
        fields_to_check = [field for field in self.Meta.fields if field != 'username']
        if not any(cleaned_data.get(field) for field in fields_to_check):
            raise forms.ValidationError("At least one field (other than username) should be updated.")

        return cleaned_data

# class ResetPasswordForm(forms.Form):
#     user_to_reset = forms.ModelChoiceField(
#         queryset=User.objects.all(),
#         label='Select User to Reset Password',
#         widget=forms.Select(attrs={'class': 'form-control'})
#     )

#     def save(self, commit=True):
#         user_to_reset = self.cleaned_data['user_to_reset']
#         user_to_reset.set_password('Nepal@123')  # Set the default password
#         if commit:
#             user_to_reset.save()
#         return user_to_reset

class ResetPasswordForm(forms.Form):
    user_to_reset = forms.ModelChoiceField(
        queryset=User.objects.all(),
        label='Select User to Reset Password',
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    new_password = forms.CharField(
        label='New Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    def save(self, commit=True):
        user_to_reset = self.cleaned_data['user_to_reset']
        new_password = self.cleaned_data['new_password']
        
        # Set the new password
        user_to_reset.set_password(new_password)

        if commit:
            user_to_reset.save()
        
        return user_to_reset


#Add Group
class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }




# TESTING BY SUWAN
class FormDataForm(forms.ModelForm):
    assigned_office = forms.ChoiceField(choices=[], required=False, label="Quater")
    num_of_add_people = forms.IntegerField(required=False)
    purpose = forms.CharField(max_length=100)




    date = forms.CharField(
        widget=forms.DateInput(format='%Y-%m-%d', attrs={'class': 'form-control nepali-datepicker'}),
        #input_formats=('%Y-%m-%d',),
        required=True  # Ensure the field is explicitly marked as required
    )
    
    province = forms.ChoiceField(
        choices=models.FormData.PROVINCE_CHOICES,
        required=False,
        widget=forms.Select(attrs={'class': 'form-select toggle-province'})
    )  
    district = forms.CharField(max_length=20, required=False, widget=forms.Select(attrs={'class': 'form-select'}))

    class Meta:
        model = models.FormData
        fields = '__all__'

   

    def clean(self):
        cleaned_data = super().clean()
        province = cleaned_data.get('province')
        district = cleaned_data.get('district')

        if not province:
            self.add_error('province', "Province cannot be Empty.")
        
        if not district:
            self.add_error('district', "District cannot be Empty.")

        return cleaned_data



    def __init__(self, *args, **kwargs):
        super(FormDataForm, self).__init__(*args, **kwargs)
        self.fields['vehicle_number'].required = False  # Set it to not required initially

        # Add classes or attributes for JavaScript to detect
        self.fields['has_vehicle'].widget.attrs['class'] = 'toggle-vehicle'
       
        self.fields['id_number'].widget.attrs['class'] = 'form-control'  # Add class for styling

        self.fields['additional_people_names'].widget.attrs['class'] = 'form-control'  # Add class for styling

        group_choices = [(group.name, group.name) for group in Group.objects.exclude(name__in=['SUPERADMIN', 'GATE ADMIN'])]
        # Add the default option
        group_choices.insert(0, ('', 'Select the quater to visit'))        
        self.fields['assigned_office'].choices = group_choices


        # Initialize the province and district choices
        province_value = self.initial.get('province') if self.initial else None
        self.set_province_choices()
        self.set_district_choices(province_value)
        self.fields['district'].widget.attrs['class'] = 'form-select'  # Add class for the select element

    def set_province_choices(self):
        self.fields['province'].choices = models.FormData.PROVINCE_CHOICES

    def set_district_choices(self, province):
        if province:
            districts = [district[1] for district in models.FormData.DISTRICT_CHOICES if district[0] == province]
            self.fields['district'].choices = [(district, district) for district in districts[0]]


    # def set_district_choices(self, province):
    #     if province:
    #         districts = models.FormData.DISTRICT_CHOICES.get(province, [])
    #         self.fields['district'].choices = [(district, district) for district in districts]
    


    
    

main/templates/user/dashboard.html
{% extends 'base.html' %}
{% block content %}
    <!-- Main Start -->
    <main>
		<!-- Services -->
		<section class="container my-4" style="margin-bottom:200px;">
			<div class="row">
				<div class="col-3">
					{% include 'user/left-sidebar.html' %}
				</div>
				<div class="col-9">
					<h3 class="mb-4 border-bottom pb-1">Dashboard</h3>
					<div class="row">
						<div class="col-md-6">
							<div class="card">
								<h5 class="card-header">Current Package</h5>
								<ul class="list-group list-group-flush">
								    <li class="list-group-item">{{current_plan.plan}}</li>
								    <li class="list-group-item">Price: {{current_plan.price}}</li>
								    <li class="list-group-item">Validity: {{current_plan.plan.validity_days}} Days</li>
								    <li class="list-group-item">Purchase Date: {{current_plan.reg_date}}</li>
								    <li class="list-group-item">Expiry Date: {{enddate}}</li>
							  	</ul>
							</div>
						</div>
						<div class="col-md-6">
							<div class="card">
								<h5 class="card-header">Assigned Trainer</h5>
								<img src="{{my_trainer.trainer.img.url}}" class="card-img-top" alt="{{my_trainer.trainer}}">
								<div class="card-body">
									<h6 class="card-text">{{my_trainer.trainer}}</h6>
								</div>
								<div class="card-footer">
									<a href="{{my_trainer.trainer.facebook}}" title="Facebook"><i class="bi bi-facebook"></i></a>
									<a href="{{my_trainer.trainer.twitter}}" title="Twitter"><i class="bi bi-twitter"></i></a>
									<a href="{{my_trainer.trainer.youtube}}"><i class="bi bi-youtube" title="YouTube"></i></a>
									<a href="{{my_trainer.trainer.pinterest}}" title="Pinterest">P</a>
									<button data-bs-toggle="modal" data-bs-target="#AchivementModal" title="Achivement" class="float-end btn btn-sm btn-success"><i class="bi bi-trophy-fill"></i></button>

<!-- Modal -->
<div class="modal fade" id="AchivementModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{my_trainer.trainer.full_name}} Achivements</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <table class="table table-hover">
        	<thead>
        		<tr>
        			<th>Title</th>
        			<th>Image</th>
        			<th>Detail</th>
        		</tr>
        	</thead>
        	<tbody>
        		{% for achive in  my_trainer.trainer.trainerachivement_set.all %}
        		<tr>
	        		<td>{{achive.title}}</td>
	        		<td><img src="{{achive.img.url}}" width="80" /></td>
	        		<td>{{achive.detail}}</td>
	        	</tr>
	        	{% endfor %}
        	</tbody>
        </table>
      </div>
    </div>
  </div>
</div>

								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!-- End -->
    </main>
    <!-- End -->
{% endblock %}

main/templates/user/left-sidebar.html
<div class="list-group">
	{% comment %} <a href="{% url 'user_dashboard' %}" class="list-group-item {% if request.path == '/user-dashboard' %} active {% endif %}">Dashboard</a> {% endcomment %}
	{% comment %} <a href="{% url 'update_profile' %}" class="list-group-item {% if request.path == '/update-profile' %} active {% endif %}">Profile</a>
	<a href="{% url 'password_change' %}" class="list-group-item {% if request.path == '/accounts/password_change/' %} active {% endif %}">Change Password</a> {% endcomment %}
	{% comment %} <a href="{% url 'notifs' %}" class="list-group-item {% if request.path == '/notifs' %} active {% endif %}">Notifications <span class="float-end badge bg-info mt-1">{{total_unread}}</span></a> {% endcomment %}
	{% comment %} <a href="#" class="list-group-item">Messages</a> {% endcomment %}
	{% comment %} <a href="{% url 'report_for_trainer' %}" class="list-group-item {% if request.path == '/report_for_trainer' %} active {% endif %}">Report for Trainer</a> {% endcomment %}

	<a href="{% url 'update_user_profile' %}" class="list-group-item {% if request.path == '/update-user-profile' %} active {% endif %}">Profile</a>
	<a href="{% url 'reset_user_password' %}" class="list-group-item {% if request.path == '/reset-password' %} active {% endif %}">Reset Password</a>

</div>

main/templates/user/reset-password.html
{% extends 'base.html' %}

{% block content %}
    <!-- Main Start -->
    <main class="container mt-4" style="margin-bottom:200px;">
        <div class="card shadow mb-4" style="background-color: #eaf6fd;">
            <div class="card-body">
              <h2 class="card-title mb-4 text-center text-uppercase font-weight-bold text-primary">Reset Password</h2>
              
              <!-- Your pass details content goes here -->
          
            </div>
        </div>
        <div class="row" style="font-weight: bold;">
            <div class="col-md-3">
                {% include 'user/left-sidebar.html' %}
            </div>
            <div class="col-md-9">
                <div class="card">
                    <div class="card-body">
                        {% if msg %}
                            <p class="text-success">{{ msg }}</p>
                        {% endif %}
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success d-block mx-auto">Reset Password</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <!-- End -->
{% endblock %}

main/templates/user/update-profile.html
{% extends 'base.html' %}
{% block content %}
    <main>
		<section class="container my-4" style="margin-bottom:200px;">
			<div class="row">
				<div class="card shadow mb-4" style="background-color: #eaf6fd;">
					<div class="card-body">
					  <h2 class="card-title mb-4 text-center text-uppercase font-weight-bold text-primary">Update Profile</h2>				  
					</div>
				</div>
					{% if msg %}
					<p class="text-success">{{ msg }}</p>
					{% endif %}
					<form method="post" action="" class="text-center">
						<table class="table table-bordered mx-auto">
							{% csrf_token %}
							<tr>
								<th>First name:</th>
								<td>{{ form.first_name }}</td>
							</tr>
							<tr>
								<th>Last name:</th>
								<td>{{ form.last_name }}</td>
							</tr>
							<tr>
								<th>Email address:</th>
								<td>{{ form.email }}</td>
							</tr>
							<tr>
								<th>Username:</th>
								<td>{{ form.username }}</td>
							</tr>
							<tr>
								<td colspan="2">
									<button type="button" class="btn btn-primary" onclick="togglePasswordFields()">Change Password</button>
								</td>
							</tr>
							<tr id="passwordFields">
								<th>New Password:</th>
								<td>{{ form.password1 }}</td>
							</tr>
							<tr id="confirmPasswordField">
								<th>Confirm New Password:</th>
								<td>{{ form.password2 }}</td>
							</tr>
							{% for field, errors in form.errors.items %}
								{% if field == 'password2' %}
									<tr>
										<td colspan="2" class="text-danger">{{ errors }}</td>
									</tr>
								{% endif %}
							{% endfor %}
							<tr>
								<td colspan="2">
									<input type="submit" class="btn btn-primary" />
								</td>
							</tr>
						</table>
					</form>
					<script>
						document.addEventListener('DOMContentLoaded', function() {
							const passwordFields = document.getElementById('passwordFields');
							const confirmPasswordField = document.getElementById('confirmPasswordField');
							
							// Initially hide the password fields
							passwordFields.style.display = 'none';
							confirmPasswordField.style.display = 'none';
						});
					
						function togglePasswordFields() {
							const passwordFields = document.getElementById('passwordFields');
							const confirmPasswordField = document.getElementById('confirmPasswordField');
							
							// Toggle the display property based on the button click
							const displayValue = passwordFields.style.display === 'none' ? 'table-row' : 'none';
							passwordFields.style.display = displayValue;
							confirmPasswordField.style.display = displayValue;
							
							// Disable or enable password input fields based on display value
							const isDisabled = displayValue === 'none';
							passwordFields.querySelector('input').disabled = isDisabled;
							confirmPasswordField.querySelector('input').disabled = isDisabled;
						}
					</script>
					
					
				</div>
		</section>
    </main>
{% endblock %}

main/templates/user/update-user-profile.html
{% extends 'base.html' %}

{% block content %}
    <!-- Main Start -->
    <main class="container mt-4" style="margin-bottom:200px;">
      <div class="card shadow mb-4" style="background-color: #eaf6fd;">
        <div class="card-body">
          <h2 class="card-title mb-4 text-center text-uppercase font-weight-bold text-primary">Update User's Profile</h2>
          
          <!-- Your pass details content goes here -->
        
        </div>
      </div>
        <div class="row" style="font-weight: bold;">
            <div class="col-md-3">
                {% include 'user/left-sidebar.html' %}
            </div>
            <div class="col-md-9">
                <div class="card">
                    <div class="card-body">
                        {% if msg %}
                            <p class="text-success">{{ msg }}</p>
                        {% endif %}
                        <form method="post" id="updateUserForm">
                            {% csrf_token %}

                            <div class="form-group" style="font-weight: bold;">
                                <label for="id_user_to_update">Select User to Update:</label>
                                {{ form.user_to_update }}
                                <div class="mt-3"></div>

                                <div class="text-center">
                                  <button type="button" class="btn btn-primary" onclick="searchUser()">Search</button>
                              </div>
                            </div>

                            <div id="userData" style="display: none;">
                                <h3>User Data</h3>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="id_first_name">First Name:</label>
                                            <input type="text" class="form-control" id="id_first_name" name="first_name" value="{{ form.instance.first_name }}" required>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="id_last_name">Last Name:</label>
                                            <input type="text" class="form-control" id="id_last_name" name="last_name" value="{{ form.instance.last_name }}" required>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="id_email">Email:</label>
                                    <input type="email" class="form-control" id="id_email" name="email" value="{{ form.instance.email }}" required>
                                </div>

                                <div class="form-group">
                                    <label for="id_username">Username:</label>
                                    <input type="text" class="form-control" id="id_username" name="username" value="{{ form.instance.username }}" readonly >
                                </div>

                                <div class="mt-3"></div>
                                <div class="text-center">

                                <button type="submit" class="btn btn-success">Update Profile</button>
                                <a href="{% url 'cancel_update' %}" class="btn btn-secondary">Cancel</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <!-- End -->

    <script>
        function searchUser() {
            var selectedUser = document.getElementById("id_user_to_update").value;

            // Implement logic to fetch user data based on selectedUser using AJAX
            // For simplicity, I'm assuming you have a URL endpoint to fetch user data
            var url = "/get_user_data/" + selectedUser + "/";

            // Use AJAX to fetch user data
            fetch(url)
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }
                    return response.json();
                })
                .then(data => {
                    // Update the form fields with fetched data
                    document.getElementById("id_first_name").value = data.first_name;
                    document.getElementById("id_last_name").value = data.last_name;
                    document.getElementById("id_email").value = data.email;
                    document.getElementById("id_username").value = data.username;


                    

                    // Display the user data section
                    document.getElementById("userData").style.display = "block";
                })
                .catch(error => console.error('Error:', error));
        }

    </script>
{% endblock %}



{% comment %} {% extends 'base.html' %}

{% block content %}
<div class="col-3">
  {% include 'user/left-sidebar.html' %}
</div>

<div class="container mt-4">
  <div class="card">
    <div class="card-body">
      <h2 class="card-title">Update User Profile</h2>

      <form method="post" id="updateUserForm">
        {% csrf_token %}

        <div class="form-group">
          <label for="id_user_to_update">Select User to Update:</label>
          {{ form.user_to_update }}
          <div class="mt-3"></div>

          <button type="button" class="btn btn-primary" onclick="searchUser()">Search</button>
        </div>

        <div id="userData" style="display: none;">
          <h3>User Data</h3>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="id_first_name">First Name:</label>
                <input type="text" class="form-control" id="id_first_name" name="first_name" required>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="id_last_name">Last Name:</label>
                <input type="text" class="form-control" id="id_last_name" name="last_name" required>
              </div>
            </div>
          </div>

          <div class="form-group">
            <label for="id_email">Email:</label>
            <input type="email" class="form-control" id="id_email" name="email" required>
          </div>

          <div class="form-group">
            <label for="id_username">Username:</label>
            <input type="text" class="form-control" id="id_username" name="username" required>
          </div>

          <div class="mt-3"></div>

          <button type="submit" class="btn btn-success">Update Profile</button>
        </div>

        {% if msg %}
          <p class="mt-3 alert alert-info">{{ msg }}</p>
        {% endif %}
      </form>
    </div>
  </div>
</div>

<script>
  function searchUser() {
    var selectedUser = document.getElementById("id_user_to_update").value;

    // Implement logic to fetch user data based on selectedUser using AJAX
    // For simplicity, I'm assuming you have a URL endpoint to fetch user data
    var url = "/get_user_data/" + selectedUser + "/";

    // Use AJAX to fetch user data
    fetch(url)
      .then(response => {
        if (!response.ok) {
          throw new Error('Network response was not ok');
        }
        return response.json();
      })
      .then(data => {
        // Update the form fields with fetched data
        document.getElementById("id_first_name").value = data.first_name;
        document.getElementById("id_last_name").value = data.last_name;
        document.getElementById("id_email").value = data.email;

        // Check if the 'username' field exists in the data object
        if ('username' in data) {
          document.getElementById("id_username").value = data.username;
        } else {
          console.error('Error: Username field not found in the server response.');
        }

        // Display the user data section
        document.getElementById("userData").style.display = "block";
      })
      .catch(error => console.error('Error:', error));
  }

</script>
{% endblock %} {% endcomment %}




{% comment %} {% extends 'base.html' %}

{% block content %}
  <h2>Update User Profile</h2>
  <form method="post" id="updateUserForm">
    {% csrf_token %}
    
    <div class="form-group">
      <label for="id_user_to_update">Select User to Update:</label>
      {{ form.user_to_update }}
      <button type="button" onclick="searchUser()">Search</button>
    </div>
    
    <div id="userData" style="display: none;">
      <h3>User Data</h3>
      {% for field in form.visible_fields %}
        <div class="form-group">
          {{ field.label_tag }}
          {{ field }}
        </div>
      {% endfor %}
      <button type="submit">Update Profile</button>
    </div>

    {% if msg %}
      <p>{{ msg }}</p>
    {% endif %}
  </form>

  <script>
    function searchUser() {
      var selectedUser = document.getElementById("id_user_to_update").value;
      
      // Implement logic to fetch user data based on selectedUser using AJAX
      // For simplicity, I'm assuming you have a URL endpoint to fetch user data
      var url = "/get_user_data/" + selectedUser + "/";
      
      // Use AJAX to fetch user data
      fetch(url)
        .then(response => {
          if (!response.ok) {
            throw new Error('Network response was not ok');
          }
          return response.json();
        })
        .then(data => {
          // Update the form fields with fetched data
          {% for field in form.visible_fields %}
            document.getElementById("id_{{ field.name }}").value = data.{{ field.name }};
          {% endfor %}
          
          // Display the user data section
          document.getElementById("userData").style.display = "block";
        })
        .catch(error => console.error('Error:', error));
    }
  </script>
{% endblock %} {% endcomment %}